[package]
name = "utxorpc-spec-sync"
version = "1.0.0-alpha.0"
edition = "2021"

[dependencies]
bytes = "^1.4"
pbjson = "^0.5"
pbjson-types = "^0.5"
prost = "^0.11"
serde = "^1.0"
tonic = "^0.9"
utxorpc-spec-cardano = { version = "1.0.0-alpha.0", path = "../../../cardano/gen/rust" }

[features]
default = []
## @@protoc_insertion_point(features)
