name: "setup protoc hololens"
description: "setup protoc hololens plugin (Haskell)"

runs:
  using: "composite"
  steps:
    - name: Setup Haskell
      id: setup-hs
      uses: haskell-actions/setup@v2
      with:
        ghc-version: 9.6.4

    - name: Restore Stack Root
      uses: actions/cache/restore@v4
      id: restore-stack
      with:
        path: ${{ steps.setup-hs.outputs.stack-root }}
        key: stack-protoc

    - name: Install Haskell plugin from Hackage
      shell: bash
      run: stack install proto-lens-protoc-0.8.0.0

    - name: Save Stack cache
      if: steps.restore-stack.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.setup-hs.outputs.stack-root }}
        key: stack-protoc
