name: 'build rust crate'
description: 'Builds the Rust crate from the codegen artifact'

runs:
  using: 'composite'
  steps:
   
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Publish to Crates.io
      working-dir: codgen/rust
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish --dry-run
