name: 'build rust crate'
description: 'Builds the Rust crate from the codegen artifact'
inputs:
  cargo-registry-token:
    description: token to authenticate to crates.io
    required: true
  dry-run:
    description: Whether to run npm publish in dry-run mode
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
   
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Publish dry run
      if: inputs.dry-run == true
      working-directory: codegen/rust
      shell: bash
      run: |
        cargo publish --dry-run --allow-dirty

    - name: Publish to Crates.io
      if: inputs.dry-run == false
      working-directory: codegen/rust
      shell: bash
      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
      run: |
        cargo publish --allow-dirty
