name: "publish haskell"
description: "Publishes Haskell codegen spec to Hackage (WIP)"
inputs:
  registry-token:
    description: token to authenticate to Hackage registry
    required: false
  mode:
    description: supported values are 'release' and 'dry-run'
    required: true

runs:
  using: "composite"

  steps:
    - name: Setup Haskell
      id: setup-hs
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-no-global: true

    - name: Restore Stack
      id: restore-stack
      uses: actions/cache/restore@v4
      working-directory: gen/haskell
      with:
        path: |
          ${{ steps.setup-hs.outputs.stack-root }}
          .stack-work
        key: stack-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: stack-root_

    - name: Get Package Version
      id: package-version
      shell: bash
      working-directory: gen/haskell
      run: |
        VERSION=$(sed -nE '/^version:\s*([0-9]\.[0-9]+\.[0-9]+.*)$/s||\1|p' utxorpc.cabal)
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Build Dependencies
      id: build-dependencies
      shell: bash
      working-directory: gen/haskell
      run: |
        stack build --only-dependencies

    - name: Build Package
      id: build
      shell: bash
      working-directory: gen/haskell
      env:
        version: ${{ steps.package-version.outputs.VERSION }}
      run: |
        export HACKAGE_TOKEN={{ secrets.HASKELL_REGISTRY_TOKEN }}
        stack test
        stack upload --candidate --test-tarball .
        stack sdist
        echo "SDIST-LOCATION=$(pwd)/dist-newstyle/sdist/utxorpc-${{ env.version }}.tar.gz" >> "$GITHUB_OUTPUT"

    - name: Upload Haskell Artifacts
      if: inputs.mode == 'release'
      uses: actions/upload-artifact@v4
      env:
        version: ${{ steps.package-version.outputs.VERSION }}
        location: ${{ steps.build.outputs.SDIST-LOCATION }}
      with:
        name: haskell-${{ env.version }}
        path: ${{ env.location }}

    - name: Cache Stack
      if: steps.restore-stack.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      working-directory: gen/haskell
      with:
        path: |
          ${{ steps.setup-hs.outputs.stack-root }}
          .stack-work
        key: stack-${{ hashFiles('stack.yaml.lock') }}
