name: 'release go code'
description: 'Pushes go code to the sdk repo'
inputs:
  repository-token:
    description: token for git authentication
    required: false
  mode:
    description: supporte values are 'release' and 'dry-run'
    required: true

runs:
  using: 'composite'
  steps:
   
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20

    - name: Attempt Build
      working-directory: codegen/go
      shell: bash
      run: |
        go get -v -t -d ./...
        go build -v ./...

    - uses: actions/checkout@v3
      with:
        repository: utxorpc/go-sdk
        fetch-depth: 0
        token: ${{ inputs.repository-token }}

    - name: Commit new spec
      shell: bash
      run: |
        rm -Rf go-sdk/spec
        mv codegen/go go-sdk/spec
        cd go-sdk
        git commit -a -m "chore: update spec codegen"

    - name: Push changes
      if: inputs.mode == 'release'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.repository-token }}
        repository: utxorpc/go-sdk
