name: "Publish Artifacts"

on:
  push:
    branches:
      - main

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          cache: "npm"

      - name: Setup Haskell
        uses: haskell-actions/setup@v2

      - name: Install Cargo
        run: curl https://sh.rustup.rs -sSf | sh

      - name: Install Buf
        run: npm install @bufbuild/buf

      - name: Install Protoc Plugins from Cargo
        run: |
          cargo install protoc-gen-prost
          cargo install protoc-gen-crate
          cargo install protoc-gen-tonic
          cargo install protoc-gen-prost-serde

      - name: Install Protoc Plugins from npm
        run: |
          npm install @connectrpc/protoc-gen-connect-es
          npm install @bufbuild/protoc-gen-es

      - name: Install Protoc Plugins from Hackage
        run: cabal install proto-lens-protoc

      - name: Generate code
        run: |
          for DIR in build cardano submit sync watch; do
            cd $DIR && ../buf generate proto
            cd ..
          done

      - name: Upload Haskell Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: haskell-codegen
          path: ./*/gen/haskell
