name: "Publish Artifacts"

on:
  push:
    branches:
      - main

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install buf
        run: |
          BIN="." && \
          VERSION="1.28.1" && \
          curl -sSL \
          "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
          -o "${BIN}/buf" && \
          chmod +x "${BIN}/buf"

      - name: List contents
        run: ls .

      # - name: Install Haskell plugin
      #   run:

      - name: Generate code
        run: |
          for DIR in build cardano submit sync watch; do
            cd $DIR && ../buf generate proto
            cd ..
          done

      - name: Upload Haskell Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: haskell-codegen
          path: ./*/gen/haskell
