name: "Publish Artifacts"

on:
  push:
    branches:
      - main

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: "npm"

      - name: Add node_modules to PATH
        run: echo "$(pwd)/node_modules/.bin" >> "$GITHUB_PATH"

      - name: Install Prost from Cargo
        uses: baptiste0928/cargo-install@v2
        with:
          crate: protoc-gen-prost

      - name: Install Tonic from Cargo
        uses: baptiste0928/cargo-install@v2
        with:
          crate: protoc-gen-tonic

      - name: Install protoc-gen-prost-crate from Cargo
        uses: baptiste0928/cargo-install@v2
        with:
          crate: protoc-gen-prost-crate

      - name: Install Prost serde from Cargo
        uses: baptiste0928/cargo-install@v2
        with:
          crate: protoc-gen-prost-serde

      - name: Install Protoc Plugins from npm
        run: |
          npm install @connectrpc/protoc-gen-connect-es
          npm install @bufbuild/protoc-gen-es

      - name: Setup Haskell
        id: setup-hs
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.6.4

      - name: Restore cached Haskell plugin
        uses: actions/cache@v4
        id: cache-proto-lens-protoc
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup-hs.outputs.ghc-version }}-cabal-${{ steps.setup-hs.outputs.cabal-version}}
        with:
          path: ${{ ~/.cabal/bin/ }}
          key: ${{ env.key }}-proto-lens-protoc

      - name: Install Haskell plugin from Hackage
        if: steps.cache-proto-lens-protoc.outputs.cache-hit != 'true'
        run: cabal install proto-lens-protoc

      - name: Cache Haskell plugin
        if: steps.cache-proto-lens-protoc.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ ~/.cabal/bin }}
          key: ${{ steps.cache-proto-lens-protoc.outputs.cache-primary-key }}

      - name: Install Buf from npm
        run: npm install @bufbuild/buf

      - name: Show node node_modules
        run: ls $(pwd)/node_modules/.bin

      - name: Generate code
        run: |
          for DIR in build cardano submit sync watch; do
            cd $DIR && buf generate proto
            cd ..
          done

      - name: Upload Haskell Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: haskell-codegen
          path: ./*/gen/haskell
