name: "Release Dry-run"

on:
  workflow_dispatch:

jobs:
  generate:
    uses: ./.github/workflows/generate.yml

  publish-dry-run:
    needs: [generate]
    uses: ./.github/workflows/publish-all.yml
    secrets: inherit
    with:
      mode: "dry-run"
