name: "publish packages"

on:
  workflow_call:
    inputs:
      mode:
        type: string
        description: supporte values are 'release' and 'dry-run'
        required: true
      cargo-registry-token:
        type: string
        required: true
      npm-registry-token:
        type: string
        required: true

jobs:
  rust-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/rust-release
        with:
          registry-token: ${{ inputs.cargo-registry-token }}
          mode: ${{ inputs.mode }}

  node-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/node-release
        with:
          registry-token: ${{ inputs.npm-registry-token }}
          mode: ${{ inputs.mode }}
