name: "Release"

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  generate:
    uses: ./.github/workflows/generate.yml

  # build-haskell:
  #   needs: [generate]
  #   uses: ./.github/workflows/build-haskell.yml

  rust-release:
    needs: [generate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: codegen

      - uses: ./.github/actions/rust-release
