name: "Release"

on:
  workflow_dispatch:
  push:
    tags: v*

jobs:
  generate:
    uses: ./.github/workflows/generate.yml

  publish-dry-run:
    needs: [generate]
    uses: ./.github/workflows/publish-all.yml
    secrets: inherit
    with:
      mode: "dry-run"

  publish:
    needs: [publish-dry-run]
    uses: ./.github/workflows/publish-all.yml
    secrets: inherit
    with:
      mode: "release"
