name: "Release"

on:
  workflow_dispatch:
  push:
    tags: v*

jobs:
  generate:
    uses: ./.github/workflows/generate.yml

  publish-dry-run:
    needs: [generate]
    uses: ./.github/workflows/publish.yml
    with:
      mode: "dry-run"

  publish:
    needs: [publish-dry-run]
    uses: ./.github/workflows/publish.yml
    with:
      mode: "release"
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      npm-registry-token: ${{ secrets.NPM_REGISTRY_TOKEN }}

  build-haskell:
    needs: [generate]
    uses: ./.github/workflows/build-haskell.yml
